/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthPasswordResetConfirmRouteImport } from './routes/auth/password-reset-confirm'
import { Route as AuthPasswordResetRouteImport } from './routes/auth/password-reset'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthEmailVerificationConfirmRouteImport } from './routes/auth/email-verification-confirm'
import { Route as AuthEmailVerificationRouteImport } from './routes/auth/email-verification'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreateOrganisationRouteImport } from './routes/_authenticated/create-organisation'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPasswordResetConfirmRoute =
  AuthPasswordResetConfirmRouteImport.update({
    id: '/auth/password-reset-confirm',
    path: '/auth/password-reset-confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthPasswordResetRoute = AuthPasswordResetRouteImport.update({
  id: '/auth/password-reset',
  path: '/auth/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEmailVerificationConfirmRoute =
  AuthEmailVerificationConfirmRouteImport.update({
    id: '/auth/email-verification-confirm',
    path: '/auth/email-verification-confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthEmailVerificationRoute = AuthEmailVerificationRouteImport.update({
  id: '/auth/email-verification',
  path: '/auth/email-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreateOrganisationRoute =
  AuthenticatedCreateOrganisationRouteImport.update({
    id: '/create-organisation',
    path: '/create-organisation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-organisation': typeof AuthenticatedCreateOrganisationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/email-verification-confirm': typeof AuthEmailVerificationConfirmRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/password-reset-confirm': typeof AuthPasswordResetConfirmRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-organisation': typeof AuthenticatedCreateOrganisationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/email-verification-confirm': typeof AuthEmailVerificationConfirmRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/password-reset-confirm': typeof AuthPasswordResetConfirmRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/create-organisation': typeof AuthenticatedCreateOrganisationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/email-verification-confirm': typeof AuthEmailVerificationConfirmRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/password-reset-confirm': typeof AuthPasswordResetConfirmRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-organisation'
    | '/dashboard'
    | '/auth/email-verification'
    | '/auth/email-verification-confirm'
    | '/auth/login'
    | '/auth/password-reset'
    | '/auth/password-reset-confirm'
    | '/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-organisation'
    | '/dashboard'
    | '/auth/email-verification'
    | '/auth/email-verification-confirm'
    | '/auth/login'
    | '/auth/password-reset'
    | '/auth/password-reset-confirm'
    | '/auth/register'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/create-organisation'
    | '/_authenticated/dashboard'
    | '/auth/email-verification'
    | '/auth/email-verification-confirm'
    | '/auth/login'
    | '/auth/password-reset'
    | '/auth/password-reset-confirm'
    | '/auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthEmailVerificationRoute: typeof AuthEmailVerificationRoute
  AuthEmailVerificationConfirmRoute: typeof AuthEmailVerificationConfirmRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPasswordResetRoute: typeof AuthPasswordResetRoute
  AuthPasswordResetConfirmRoute: typeof AuthPasswordResetConfirmRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/password-reset-confirm': {
      id: '/auth/password-reset-confirm'
      path: '/auth/password-reset-confirm'
      fullPath: '/auth/password-reset-confirm'
      preLoaderRoute: typeof AuthPasswordResetConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/password-reset': {
      id: '/auth/password-reset'
      path: '/auth/password-reset'
      fullPath: '/auth/password-reset'
      preLoaderRoute: typeof AuthPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/email-verification-confirm': {
      id: '/auth/email-verification-confirm'
      path: '/auth/email-verification-confirm'
      fullPath: '/auth/email-verification-confirm'
      preLoaderRoute: typeof AuthEmailVerificationConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/email-verification': {
      id: '/auth/email-verification'
      path: '/auth/email-verification'
      fullPath: '/auth/email-verification'
      preLoaderRoute: typeof AuthEmailVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create-organisation': {
      id: '/_authenticated/create-organisation'
      path: '/create-organisation'
      fullPath: '/create-organisation'
      preLoaderRoute: typeof AuthenticatedCreateOrganisationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCreateOrganisationRoute: typeof AuthenticatedCreateOrganisationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCreateOrganisationRoute: AuthenticatedCreateOrganisationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthEmailVerificationRoute: AuthEmailVerificationRoute,
  AuthEmailVerificationConfirmRoute: AuthEmailVerificationConfirmRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPasswordResetRoute: AuthPasswordResetRoute,
  AuthPasswordResetConfirmRoute: AuthPasswordResetConfirmRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
